on: pull_request
name: Run checks
jobs:
  go-checks:
    name: Run go checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Go Modules Vendor
      uses: ./
      env:
        IMPORT: cedrickring/golang-action
        PROJECT_PATH: ./tests/projects/go_modules_vendored
    - name: Test Go Modules
      uses: ./
      env:
        IMPORT: cedrickring/golang-action
        PROJECT_PATH: ./tests/projects/go_modules
    - name: Test Go Standard
      uses: ./
      env:
        IMPORT: cedrickring/golang-action
        PROJECT_PATH: ./tests/projects/go_standard
  action-checks:
    name: Run action checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dockerfile_lint
      run: sudo npm i -g dockerfile_lint
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Docker Build
      run: make build
