on: release
name: Publish to Docker Hub
jobs:
  publish:
    name: Publish docker images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dockerfile_lint
      run: sudo npm i -g dockerfile_lint
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Build
      run: make build
    - name: Docker Tag
      run: make docker-tag
    - name: Docker Publish
      run: make publish